---
http_interactions:
- request:
    method: post
    uri: http://<URL>/virtual_machines/404/build.json?virtual_machine%5Btemplate_id%5D=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Basic <REDACTED>
  response:
    status:
      code: 404
      message: Not Found
    headers:
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      X-Powered-By:
      - Phusion Passenger (mod_rails/mod_rack) 3.0.1
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Wed, 20 Apr 2011 15:54:19 GMT
      Server:
      - Apache/2.2.3 (CentOS)
      X-Runtime:
      - '2.751480'
      Set-Cookie:
      - "<REDACTED>"
      Cache-Control:
      - no-cache
      Status:
      - '404'
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"error":"Resource not found"}'
    http_version: '1.1'
  recorded_at: Fri, 21 Feb 2020 07:20:38 GMT
- request:
    method: post
    uri: http://<URL>/virtual_machines/72/build.json?virtual_machine%5Btemplate_id%5D=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Authorization:
      - Basic <REDACTED>
  response:
    status:
      code: 201
      message: Created
    headers:
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Location:
      - https://www.example.com/virtual_machines/72
      X-Powered-By:
      - Phusion Passenger (mod_rails/mod_rack) 3.0.1
      Content-Type:
      - application/json; charset=utf-8
      X-Runtime:
      - '0.163372'
      Server:
      - Apache/2.2.3 (CentOS)
      Date:
      - Wed, 20 Apr 2011 16:02:18 GMT
      Set-Cookie:
      - "<REDACTED>"
      Status:
      - '201'
      Cache-Control:
      - no-cache
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"virtual_machine":{"label":"Testingagain","cpus":1,"operating_system_distro":"rhel","created_at":"2011-04-20T16:01:10Z","template_id":1,"operating_system":"linux","cpu_shares":1,"updated_at":"2011-04-20T16:02:18Z","memory":256,"local_remote_access_port":5901,"allowed_swap":true,"recovery_mode":false,"allow_resize_without_reboot":true,"xen_id":null,"id":72,"hypervisor_id":6,"user_id":4,"template_label":"CentOS
        5.5 x64","hostname":"testingagain.com","booted":false,"remote_access_password":"sadf234","min_disk_size":5,"initial_root_password":"213fsdfsd","identifier":"asdfdsfsdf","locked":true,"built":false}}'
    http_version: '1.1'
  recorded_at: Fri, 21 Feb 2020 07:20:38 GMT
recorded_with: VCR 6.0.0
